make clean
make
echo Finish Compilation
echo ........
echo ........
echo ........
echo ........
echo ........
echo ........
echo ........
echo ........
echo ........
echo Running Assembler
./asm ./resources/mem.txt ./programs/bubble.asm
