make clean
make
echo Finish Compilation
echo ........
echo ........
echo ........
echo ........
echo ........
echo ........
echo ........
echo ........
echo ........
echo Running Simulator
./sim	./sim_resource/memin.txt ./sim_resource/memout.txt ./sim_resource/regout.txt ./sim_resource/trace.txt ./sim_resource/count.txt
