make clean
make
echo Finish Compilation
echo ........
echo ........
echo ........
echo ........
echo ........
echo ........
echo ........
echo ........
echo ........
echo Running Simulator
./sim ./resources/meminref.txt ./resources/memout.txt ./resources/regout.txt ./resources/trace.txt ./resources/count.txt
echo ....
